### ISSUE TITLE
clean up the use of members in the Role object

### ISSUE THREAD

**Issue by havetisyan** [AthenZ/athenz#1122]
right now when sending Role object back the server correctly includes the roleMembers array with all member details (e.g. expired, disabled, etc), but also includes the members field which is just the list of member names (old backward compatibility). This is causing incorrect usage when clients use the members field for easier access but start ignoring expiration, disabled states of the members.

At this time we should remove this field and not longer set it. This will force all clients to use the roleMembers field correctly.

**Comment by havetisyan** [comment]
@tatyano just an fyi that you can make sure you guys are not using the members field and only use the roleMembers field in the Role object. we'll probably remove this field at the end of October.

**Comment by tatyano** [comment]
@havetisyan Thank you for the notice.
We'll make sure our in-house client implementations will adjust to the new interface by the time we update our ZMS.
However, does this mean that the ZMS clients for each language will lose backward compatibility with the old versions?
If yes, please let us know so we can specify the version of the client libraries to prevent our developers to automatically pull them.

**Comment by havetisyan** [comment]
No, there is no backward compatibility issue - it's just we're expecting you were using the, for example in java, getRoleMembers() method to look at the members and look at their expiration, instead of just calling getMembers() and assuming all users there are valid. So this promotes the correct use of the members and looking at their expiration state.

Additionally, we strongly recommend to upgrade your client to the latest release and start taking advantage of new system disabled flag. While the go version does not require any updates, it correctly skipped any unknown attributes, if you're using the java version, you must update your client so it can start skip unknown fields in the json file and will give you more flexibility for future upgrades.
