### ISSUE TITLE
Memory leak when SSL Connection Logger is enabled

### ISSUE THREAD

**Issue by OferLevi85** [AthenZ/athenz#1331]
We found a memory leak caused by maps in JettyConnectionLogger overflowing as the result of connection events not firing as expected.

**Comment by OferLevi85** [comment]
We rewrote the Logger so instead of storing connection info in maps we simply write it to log directly on SSL handshake failures - https://github.com/AthenZ/athenz/pull/1325

**Comment by abvaidya** [comment]
Addressed in #1325
