### ISSUE TITLE
Integration - Support DataDog as a Metric collection server for Athenz

### ISSUE THREAD

**Issue by abvaidya** [AthenZ/athenz#1345]
Add supporting code in athenz which can enable Athenz components ( ZMS, ZTS, UI ) to expose metrics data to DataDog implementation.

Expectations
- Code should be accompanied with full test coverage
- Design documentation is encouraged

**Comment by patrasap0908** [comment]
Hi @abvaidya, could you elaborate a bit more here please?
Like what would be needed on the configuration side of things as far as DataDog goes?
Maybe a few example metrics that you have in mind?
