### ISSUE TITLE
Log full assertion(s) body in audit logs when assertion / policy is deleted

### ISSUE THREAD

**Issue by abvaidya** [AthenZ/athenz#1368]
Today when assertion / policy is deleted, audit logger does not log the full json body for assertion / policy.

https://github.com/AthenZ/athenz/blob/master/servers/zms/src/main/java/com/yahoo/athenz/zms/DBService.java#L2752-L2755
https://github.com/AthenZ/athenz/blob/master/servers/zms/src/main/java/com/yahoo/athenz/zms/DBService.java#L1890

This issue is to update the code to get policy / assertion full details from DB before deleting and log into audit log so that domain administrators can get all details from the audit log later.

Expecation:
- Changed code and relevant unit tests with 100% code coverage

**Comment by es-karthic** [comment]
I could check this out it looks not claimed yet
