### ISSUE TITLE
Failure building Athenz docker image

### ISSUE THREAD

**Issue by OferLevi85** [AthenZ/athenz#1376]
Following the steps in docker/Readme.md didn't work.

1. The instructions suggest using an old tag:
`P.S. the latest code may cause docker build to fail, please use older version by specifying the tag version (< v1.9.27) or post an issue
 make build TAG=v1.9.27`

But using an older tag fails because the docker/util/rdl-athenz-go-model directory didn't exist until a month ago and the images require it.
Probably just need to remove this instruction.

2. When running "make build" without tag the build still fails on the following:
`executor failed running [/bin/sh -c mvn install -pl core/zms -pl core/zts -pl libs/java/auth_core -pl libs/java/client_common -pl libs/java/server_common -pl libs/java/instance_provider -pl libs/java/cert_refresher -pl clients/java/zms -pl servers/zms -pl clients/java/zts/core -pl servers/zts -pl containers/jetty -pl assembly/zms -pl assembly/zts -Dmaven.test.skip=true -Djacoco.skip=true]: exit code: 1
make: *** [build] Error 1`
This happens because it looks for the directories under the "docker" directory instead of the main athenz directory

I think it's related to the changes in https://github.com/AthenZ/athenz/pull/1373.
When trying to build from a previous commit, I pass this stage but get an error on creating tar archive:
` => [5/9] RUN mkdir -p /tmp/zms     && mkdir -p /tmp/zts     && mkdir -p /opt/athenz/zms     && mkdir -p /opt/athenz/zts                                                                                 0.6s
 => ERROR [6/9] RUN tar xvzf ./assembly/zms/target/athenz-zms*-bin.tar.gz -C /tmp/zms     && mv /tmp/zms/athenz-zms-*/* /tmp/zms/     && mv /tmp/zms/etc /opt/athenz/zms/etc     && mv /tmp/zms/conf /o  1.0s
------`

**Comment by abvaidya** [comment]
yeah, I didnt get a chance to fix the docker build yet after #1373 , It needs to be included in the docker build.
