### ISSUE TITLE
Athenz installation problem - ReferenceError: TextEncoder is not defined

### ISSUE THREAD

**Issue by JoeWar99** [AthenZ/athenz#1720]
Hi there, we were trying to run athenz locally, and when running "mvn clean install" we get the following error:

![image](https://user-images.githubusercontent.com/48472671/147677863-f5cd6ba6-6494-4c0a-a71e-fd8025e5eee5.png)

![image](https://user-images.githubusercontent.com/48472671/147677907-07fb32d4-1361-441d-b14e-248648bae7ef.png)

Any inputs on how to solve this?

**Comment by havetisyan** [comment]
What versions of node and npm do you have installed?

node -v
npm -v
