### ISSUE TITLE
Athenz installation problem - illegal option -o pipefail

### ISSUE THREAD

**Issue by LuisPRamos** [AthenZ/athenz#1721]
When trying to run the script `start-local-athenz.sh` the following error appeared:

![image](https://user-images.githubusercontent.com/49035388/147685253-ee5caeb5-91cc-4353-9a0b-f1bc80e304eb.png)

Upon further research it appears that this is a problem with `sh` in newer versions of ubuntu. After changing the script line from `#!/bin/sh` to `#!/bin/bash` the script behaved as expected, but showed errors in other scripts that used the same shell.

The script only ran successfully when I:  
- Changed scripts that use the `set -o pipefail` command to `bash`  
- Changed `docker/Makefile` to use `bash` instead of `sh` when running scripts on my computer  
- Changed the `BASE_DIR` to my Athenz folder location

**Comment by havetisyan** [comment]
@abvaidya do we need to keep the default sh in these scripts (looks like on ubuntu the default is dash which doesn't support pipe fail)? We can either switch to bash or just drop the pipefail option - is this required?

**Comment by abvaidya** [comment]
I dont see any harm moving to bash. Will do a trial run and see if we run into any issue.
