### ISSUE TITLE
Athenz installation problem - zms-go-client fails

### ISSUE THREAD

**Issue by claudiarmamede** [AthenZ/athenz#1723]
Hi! I'm installing Athenz (with mvn clean install) but I keep getting this error and I'm not sure what to do next. Zms-go-client fails during build.

![Screenshot from 2021-12-30 12-34-24](https://user-images.githubusercontent.com/33558234/147752468-cf7f7ecd-4f6c-4111-8a15-5012d8870beb.png)

I installed the latest go version and have GOPATH=/home/claudiarmamede/go + GOROOT=/usr/local/go
I'm also using Ubuntu (VERSION="20.04.3 LTS (Focal Fossa)")

**Comment by havetisyan** [comment]
rdl/rdl-gen-athenz-go-model is the second module that is built in the project. Can you show me the output from that module? Did it built successfully? 

More importantly, the build process expects that your $GOPATH/bin is in your $PATH. See the Go section in our guide: https://github.com/AthenZ/athenz/blob/master/docs/dev_environment.md.

**Comment by claudiarmamede** [comment]
Thank you, my PATH var was not properly updated!
