### ISSUE TITLE
Athenz installation problem: athenz-auth-core-nodejs build failed

### ISSUE THREAD

**Issue by JoaoRicardoCardoso** [AthenZ/athenz#1728]
Hello! I'm having a problem building Athenz. In the athenz-auth-core-nodejs module, 2 tests fail with these error messages:

![image](https://user-images.githubusercontent.com/45019363/147886141-5e8088b0-b1c2-4ff8-b8c6-5935daef5117.png)

Any help is much appreciated!

OS: Ubuntu-20.04 64-bit running on a VM in Windows 10 
Java version: 1.8.0_202
Maven version: 3.8.4
Go version: 1.17.5
Node version: v16.13.1
Npm version: 8.1.2

**Comment by havetisyan** [comment]
Hi @JoaoRicardoCardoso 

We don't yet support node 16.x. Please downgrade to 14.x.

You can follow our dev setup for our CI/CD pipeline.

Start with the openjdk:8 docker image and then install the necessary components:
https://github.com/AthenZ/athenz/blob/master/screwdriver/scripts/install_deps.sh

this will give you the same build setup that we use to build/test and publish athenz packages.

**Comment by JoaoRicardoCardoso** [comment]
Thanks for the answer. Downgrading node fixed the problem.
