### ISSUE TITLE
The copyright text in the license file is incorrect.

### ISSUE THREAD

**Issue by munierujp** [AthenZ/athenz#1856]
The copyright text in the license file is incorrect.

https://github.com/AthenZ/athenz/blob/6fac69959050796bbd8cda4334125db02b7e666d/LICENSE#L190

## What is correct?

Replace placeholders with your own identifying information.

>To apply the Apache License to specific files in your work, attach the following boilerplate declaration, replacing the fields enclosed by brackets "[]" with your own identifying information. (Don't include the brackets!)

https://www.apache.org/licenses/LICENSE-2.0

**Comment by abvaidya** [comment]
@munierujp I think the LICENSE file is correct. That section talks about how to apply the license to individual files. e.g. https://github.com/AthenZ/athenz/blob/master/libs/java/auth_core/src/main/java/com/yahoo/athenz/auth/Authority.java#L2

**Comment by munierujp** [comment]
@abvaidya Oh, I must have made a big mistake 😱
