### ISSUE TITLE
Security vulnerabilities in zts-rolecert

### ISSUE THREAD

**Issue by aravindb26** [AthenZ/athenz#2027]
Description:

https://github.com/AthenZ/athenz/blob/master/utils/zts-rolecert/zts-rolecert.go

There are several potential security vulnerabilities in the zts-rolecert code. These vulnerabilities include:

    Lack of SSL/TLS certificate validation when making HTTPS requests to the ZTS server.
    Failure to properly parse command line arguments using the flag package.
    Generation of potentially weak random numbers using rand.Reader without specifying the length of the random number.
    Lack of input validation and sanitization on file names passed to the os.Open function.
    Lack of input validation and sanitization on the ztsURL variable passed to the net.Dial function.

Impact:

These vulnerabilities could potentially allow an attacker to intercept HTTPS requests to the ZTS server and return malicious responses, access sensitive files on the system, and make unintended connections.

Recommendation:

To fix these issues, the following actions should be taken:

    Implement SSL/TLS certificate validation when making HTTPS requests to the ZTS server using certificate pinning or by checking the certificate against a trusted certificate authority.
    Properly parse command line arguments by calling the flag.Parse() function.
    Specify the length of the random number when calling the rand.Reader function.
    Perform input validation and sanitization on file names passed to the os.Open function.
    Perform input validation and sanitization on the ztsURL variable passed to the net.Dial function.

Steps to reproduce:

    Compile and run the zts-rolecert code.
    Pass in malicious input as a command line argument or file name.
    Observe that the vulnerabilities are present.

**Comment by havetisyan** [comment]
Can you elaborate where did you see that the tool is lacking certificate validation when making https requests or failure to property parse the command line arguments? for example, your recommended action of calling flag.Parse() function which is what the tool does on line 77.
