### ISSUE TITLE
[Bug Fixed] Improperly Controlled Modification of Object Prototype Attributes ('Prototype Pollution')

### ISSUE THREAD

**Issue by iot-defcon** [AthenZ/athenz#2045]
## Describe The Bugs
qs before `6.10.3` allows attackers to cause a Node process hang because an __ proto__ key can be used. In many typical web framework use cases, an unauthenticated remote attacker can place the attack payload in the query string of the URL that is used to visit the application, such as a[__proto__]=b&a[__proto__]&a[length]=100000000. The fix was backported to qs 6.9.7, 6.8.3, 6.7.3, 6.6.1, 6.5.3, 6.4.1, 6.3.3, and 6.2.4.

```
supertest@6.2.4 requires qs@6.9.3 via a transitive dependency on formidable@2.0.1
body-parser@1.20.0 requires qs@6.10.3
express@4.18.1 requires qs@6.10.3 via body-parser@1.20.0
express@4.18.1 requires qs@6.10.3
supertest@6.2.4 requires qs@^6.10.3 via superagent@8.0.0
request@2.88.2 requires qs@~6.5.2
webdriver-manager@12.1.8 requires qs@~6.5.2 via request@2.88.2
```
[#qs](https://github.com/OrderOfTheOverflow/athenz/blob/master/ui/package-lock.json)

**Comment by havetisyan** [comment]
Thanks for the report. I believe this was already reported through Github security dependabot alerts and fixed as part of that.
