### ISSUE TITLE
Primary key not defined in schema for updating

### ISSUE THREAD

**Issue by ysknkd** [AthenZ/athenz#2060]
Hi. The `principal_group_member` has a primary key defined, but It appears that the primary key is not defined in the Schema for updating.

https://github.com/AthenZ/athenz/blob/0ff7ff4f9658fd42e8ee2161d870a89dce5167e4/servers/zms/schema/updates/update-20200827.sql#L24-L46

https://github.com/AthenZ/athenz/blob/0ff7ff4f9658fd42e8ee2161d870a89dce5167e4/servers/zms/schema/zms_server.sql#L415

Could you please provide a DDL for updating that adds the following primary key?

```sql
ALTER TABLE zms_server.principal_group_member ADD PRIMARY KEY (`group_id`, `principal_id`);
```

**Comment by havetisyan** [comment]
Thanks @ysknkd. Not sure how this happened since for CREATE command we typically just take the command from the zms_server.sql which has the primary key set.

**Comment by ysknkd** [comment]
Thank you for resolving the issue.
