### ISSUE TITLE
Question about components UMS

### ISSUE THREAD

**Issue by ysknkd** [AthenZ/athenz#2100]
While investigating the Athenz UI, It seems to rely on a component called UMS, but it is not published as a server component of Athenz. Could you please provide information on the functionality of UMS, and whether there are plans to make them publicly available in the future? I would appreciate any guidance on this matter.

**Comment by havetisyan** [comment]
UMS is the user access management system. it uses athenz to configure what users are provisioned on hosts for ssh login and sudo access. it's heavily dependent on sshca - you'll some of the those components being by the Yahoo Paranoids organization (https://github.com/theparanoids). Once all those components are open-sourced, we'll look into open sourcing UMS as well.

**Comment by ysknkd** [comment]
Thank you for taking the time to provide such a thorough response regarding the question about components UMS.
