### ISSUE TITLE
Cannot use PrincipalGroups in the Athenz Template

### ISSUE THREAD

**Issue by hiragi-gkuth** [AthenZ/athenz#2182]
In the current Athenz implementation, [PrincipalGroups](https://athenz.github.io/athenz/principal_groups/) cannot be added as RoleMember to an Athenz Template's Role. This requires multiple calls to putRole / putPolicy etc. when complex domain definitions are needed. To resolve this, I would like to enable the use of PrincipalGroups in Athenz Templates.

I think the issue is due to specifying the CompoundName type as the request body for the putDomainTemplate API in the RDL as follows:

The putDomainTemplate API accepts a DomainTemplate as the body.
https://github.com/AthenZ/athenz/blob/498e14e0a1d19bcb15b027839f0587cab79a9d68/core/zms/src/main/rdl/Domain.rdli#L232-L236

The value field of TemplateParam is a `CompoundName` .
https://github.com/AthenZ/athenz/blob/498e14e0a1d19bcb15b027839f0587cab79a9d68/core/zms/src/main/rdl/Template.tdl#L35-L43

However, the type of PrincipalGroups is `GroupName` .
https://github.com/AthenZ/athenz/blob/498e14e0a1d19bcb15b027839f0587cab79a9d68/core/zms/src/main/rdl/Names.tdl#L59-L60

I'm planning to fix this by accepting PrincipalGroups in putDomainTemplate and adding them to the Role. Are there any implementation concerns or issues that would conflict with the design philosophy of Athenz with this change?

**Comment by havetisyan** [comment]
You're describing a use case where a role member is a variable defined in a template and you want the user to specify the role member as a group as part of the template arguments?

**Comment by hiragi-gkuth** [comment]
Thank you for your response.

> You're describing a use case where a role member is a variable defined in a template and you want the user to specify the role member as a group as part of the template arguments?

That's true.

**Comment by havetisyan** [comment]
it looks like when we added support for Groups as role members the template rdl was not updated accordingly. What was your proposed fix for the issue?

**Comment by hiragi-gkuth** [comment]
I'm considering modifying the `putDomainTemplate()` to accept not only `CompoundName` but also `GroupName` in the value field of the `TemplateParam` in the `DomainTemplate` type.
I'm still thinking about the specific approach as I have not fully understood the implementation yet, but currently, I think it would be good to change the type of the value field of `TemplateParam` from `CompoundName` to `MemberName` [defined in Names.tdli](https://github.com/AthenZ/athenz/blob/master/core/zms/src/main/rdl/Names.tdl#L67), and modify the implementation of ZMSImpl.java and others accordingly.
However, since the value field of TemplateParam can be replaced not only as a value of RoleMember but also as a value of other fields of Role, Policy, or Service, I think we may need to be more cautious.

**Comment by havetisyan** [comment]
Using MemberName is somewhat misleading. It implies only role members while I can have services, policy names, etc as template parameters. So I would suggest to define a new type e.g. TemplateParamValue which then could be defined as multiple types ORed together.

**Comment by hiragi-gkuth** [comment]
Thank you for your reply. I didn't fully consider the case where other values might be involved with MemberName. I plan to move forward with the implementation as you have proposed.
I appreciate your suggestion.
