### ISSUE TITLE
Underscores are allowed in Athenz Service Names

### ISSUE THREAD

**Issue by ysknkd** [AthenZ/athenz#2183]
Athenz has the capability to issue X.509 certificates, and the Athenz Service name is used in SAN:DNS in Service Certificates.
https://github.com/AthenZ/athenz/blob/498e14e0a1d19bcb15b027839f0587cab79a9d68/utils/zts-svccert/zts-svccert.go#L186

Currently, Athenz does not perform checks for underscores when creating Services. Is this an intentional allowance for backward compatibility?
https://github.com/AthenZ/athenz/blob/6e99e643a8e93350f08c59a4fc284edf9c323590/servers/zms/src/main/java/com/yahoo/athenz/zms/ZMSImpl.java#L5690-L5697

**Comment by havetisyan** [comment]
We didn't change the RDL spec for backward compatibility but I believe the intent was to block creating domains and services with underscores. I see we have the check in domain creation but not services. I'll look into this in more detail.

**Comment by havetisyan** [comment]
https://github.com/AthenZ/athenz/pull/2191

**Comment by ysknkd** [comment]
I will try introducing it in-house after the release. I will now close this issue.
