### ISSUE TITLE
 Intent Behind Prohibiting Wildcards in Group Members

### ISSUE THREAD

**Issue by ysknkd** [AthenZ/athenz#2184]
The use of wildcards is not allowed in group members in Athenz. Could this be because roles should be used in scenarios where wildcards would be utilized? I would appreciate it if you could explain the intent behind this restriction on wildcards.
https://github.com/AthenZ/athenz/blob/498e14e0a1d19bcb15b027839f0587cab79a9d68/docs/principal_groups.md?plain=1#L46-L48

**Comment by havetisyan** [comment]
Groups can be included in lots of roles. It's a preferred way to organize your users into teams and grant them access in multiple roles in multiple domains, etc.

When we were looking at the security implications of introducing groups, one concern was that users might include * users in groups without realizing the impact of it. The user might think role1 includes group1 and I need sports.* in my role, so I'll just update group1 to include  sports.* without realizing that group1 is included in 10 different roles and now sports.* got access to all those roles. So this is why we decided explicitly to block access to any wildcards in groups.

**Comment by ysknkd** [comment]
Thank you for the detailed explanation. Indeed, the unintended impact of wildcards can be significant when groups are included in multiple roles. I understand now, so I will close this issue.
