### ISSUE TITLE
Migration to HttpClient5

### ISSUE THREAD

**Issue by ysknkd** [AthenZ/athenz#2186]
Driven by pure curiosity, I was wondering if you could shed some light on when Athenz might be planning to transition to HttpClient5, should such information be available. The reason behind my inquiry is that, as of version 3.1, SpringBoot has removed its dependency on HttpClient4. Subsequently, I anticipate that other Open Source Software (OSS) currently using HttpClient4 will also gradually transition.
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.1-Release-Notes

In the case of Athenz, I noticed that there are parts of the code generated by RDL which are dependent on HttpClient4. Therefore, I presume that the transition to HttpClient5 for Athenz might only happen after RDL has been updated to support HttpClient5. However, if there are any specific plans around this, I would greatly appreciate if you could share them.

**Comment by havetisyan** [comment]
At this point we have no plans to migrate to HttpClient5. We're not necessarily looking for any new features that may only exist in 5 and 4 is still supported as far as major defects and security bugs. I'm thinking whenever HttpClient4 is announced as EOL then we'll migrate to HttpClient5.

**Comment by ysknkd** [comment]
Thank you for your response. I will close this issue now.
