### ISSUE TITLE
Request for Separation of Signing Keys for JWT and Traditional Role Tokens and Policies

### ISSUE THREAD

**Issue by ysknkd** [AthenZ/athenz#2208]
The current implementation uses the same signature key for Role Token and Access Token (JWT), but we would like to separate them.

In our environment, Role Token are widely used, but we are considering migrating to Access Token. At that time, we want to change the signature key for Access Token, but with the current implementation, the same key is used for Role Tokens and Access Tokens. If we change the signature key in this state, it would also impact providers verifying Role Tokens. The specific impact is that we would need to distribute verification keys before changing the signature key.

Therefore, would you kindly consider allowing us to separate the keys used for traditional Role Token and Policy from those used for JWT formatted Access Token, ID Token, and Policy? We greatly appreciate your attention to this matter.

**Comment by havetisyan** [comment]
I'm not sure if I understand what is the issue and why you need separate keys for role tokens and access tokens. It's a standard security policy to periodically rotate the signing keys with the typical process of:
a) first generating a new private key in your Key Management Store and register the public key in Athenz with a new version
b) distribute the new public key (preferred option would be for services to fetch the keys directly from ZTS and not some distribution package but both models can be used). 
c) announce a date where all properties must update their public key packages.
d) on that announced date, configure the ZTS server to use the new key version to sign tokens.
So I'm expecting that you're doing this at least once a year to rotate your keys. So having those same keys to sign access tokens, makes no difference in the context of security or key rotation.

**Comment by havetisyan** [comment]
https://github.com/AthenZ/athenz/pull/2222

**Comment by havetisyan** [comment]
With the new config options, you can define role tokens and json policy files to be signed with rsa keys while json web objects using ec keys

**Comment by ysknkd** [comment]
Thank you for your assistance. I will close this now.
