### ISSUE TITLE
Support PKCS#8-formatted private key

### ISSUE THREAD

**Issue by haruyama480** [AthenZ/athenz#2217]
Newer openssl(>=3) generate RSA private key beginning with 'PRIVATE KEY', with default behavior.

But, athenz support only private keys beginning with 'RSA PRIVATE KEY' (or 'EC PRIVATE KEY' for ecdsa).
https://github.com/AthenZ/athenz/blob/82e94ed90b763478902b335583871aa40cd24ae2/libs/go/zmssvctoken/signer.go#L51-L57

The former format is called PKCS#8, The later is PKCS#1. ref. https://stackoverflow.com/a/20065522
It is possible to generate PKCS#1 key by running 'openssl genrsa' with option '--traditional'.
However, It will be great for athenz to support PKCS#8, which is generated with default behavior.

### sample command
```
% openssl version
OpenSSL 3.1.1 30 May 2023 (Library: OpenSSL 3.1.1 30 May 2023)
% openssl genrsa -out tmp 2048 && head -1 tmp
-----BEGIN PRIVATE KEY-----
% openssl genrsa --traditional -out tmp 2048 && head -1 tmp
-----BEGIN RSA PRIVATE KEY-----
```

```
# openssl version
OpenSSL 1.0.2k-fips  26 Jan 2017
# openssl genrsa -out tmp 2048 && head -1 tmp
(略)
-----BEGIN RSA PRIVATE KEY-----
```

**Comment by havetisyan** [comment]
It's been on our list to support pkcs#8 but it's has low priority. the bouncecastle library we use in auth-core has full support for it so it can be easily added. if you want to provide a PR to add support, it'll be great, otherwise I don't expect us to add support in a near future.

**Comment by haruyama480** [comment]
Thank you for quick response!

I can create a PR around the go code, referring following implemetaion.
https://github.com/golang/go/blob/5b72f45dd17314af39627c2fcac0fbc099b67603/src/crypto/tls/tls.go#L343-L349

I'm wondering if it's acceptable to make PR to support PKCS#8 in only go.

**Comment by havetisyan** [comment]
Yes, you can only update the go part if that's all is necessary for your work.
