### ISSUE TITLE
Unable to reverse lookup role list with a principal name matching the wildcard

### ISSUE THREAD

**Issue by ysknkd** [AthenZ/athenz#2245]
When adding members to a role, it is possible to use wildcards in the member names. However, even when executing getPrincipalRoles with a principal name that matches the wildcard, it is not possible to retrieve a list of roles.

For instance, when a member with a wildcard, such as `athenz.test-service*` , is added to `athenz:role.test-role` , executing getPrincipalRoles with the principal name `athenz.test-service-2` does not return `athenz:role.test-role` as a role to which the principal belongs. Instead, it results in a 404 error.

The likely cause of this issue, we believe, is that the principal_id of `athenz.test-service*` and `athenz.test-service-2` being different.

https://github.com/AthenZ/athenz/blob/bfa83a8dae13e8fc2e0ebe219037a979c1ad7a1f/servers/zms/src/main/java/com/yahoo/athenz/zms/store/impl/jdbc/JDBCConnection.java#L250-L259

**Comment by havetisyan** [comment]
Yes. The lookup roles principal api only returns the roles that that given principal is explicitly included. It cannot take into account wildcards. To provide such functionally the system needs to go through all the principles with wildcards and see which one matches the given one. 

We actually discourage the use of wildcards. There are only a few cases where we actually expect the principal to include wildcards, a primary one being ‘*’ to allow everyone. 

A better choice if you want to take into account wildcards is to use the role access api in ZTS which handles the principal in a given domain only and does process wildcards as expected.

**Comment by ysknkd** [comment]
Thank you for your response. I understand and will close this now.
