### ISSUE TITLE
The Screwdriver job has failed and v1.11.50 has not been published

### ISSUE THREAD

**Issue by ysknkd** [AthenZ/athenz#2486]
The Screwdriver job has failed and v1.11.50 has not been published.
https://cd.screwdriver.cd/pipelines/6606/builds/917869/steps/publish

Therefore, the relevant version has not been published to Maven either.
![image](https://github.com/AthenZ/athenz/assets/501181/f07658f5-6ef7-45c6-a35a-f54cfe6a1849)
https://mvnrepository.com/artifact/com.yahoo.athenz/athenz-auth-core

**Comment by havetisyan** [comment]
Yes, I’m aware of it. Maven central was slow today and it kept timing out when publishing the artifacts. So we’ll try running the job again tomorrow
