### ISSUE TITLE
Athenz UI build forced to stop when using Screwdriver.cd

### ISSUE THREAD

**Issue by ysknkd** [AthenZ/athenz#2542]
By default, Jest runs tests in 64 workers, which can sometimes consume too much of the resources in the Screwdriver.cd execution containers, leading to incomplete tests.
https://cd.screwdriver.cd/pipelines/6606/builds/926683/steps/build

![image](https://github.com/AthenZ/athenz/assets/501181/e5956333-54b2-42f1-b588-dfa8f1ae93f8)

I suggest using the `--maxWorkers` option to limit the number of parallel processes. In our environment, setting `--maxWorkers=8` has proven to stabilize the builds on Screwdriver.cd.
https://github.com/AthenZ/athenz/blob/073a1741ed7bfd09ab5b1ba2c5733223ab4ffca1/ui/package.json#L29

**Comment by ysknkd** [comment]
I truly appreciate your assistance with the issue that I raised.

**Comment by havetisyan** [comment]
Thank you for reporting and providing a solution!
