### ISSUE TITLE
Cannot update RoleMeta with blank SignAlgorithm

### ISSUE THREAD

**Issue by WoWsj** [AthenZ/athenz#2566]
Hello, I'm trying to use go client for Athenz.

When I tried to use `PutRoleMeta` or `PutRole` method for zms client, it return this error.

trying to...
```
        role, err := client.GetRole(testDomain, "admin", nil, nil, nil)
	if err != nil {
		fmt.Println(err.Error())
		return
	}

	role.SignAlgorithm = ""
	role.Tags = map[zms.TagKey]*zms.TagValueList{"test": {List: []zms.TagCompoundValue{"tag1", "tag2"}}}
	flag := true
	updated, err := client.PutRole(testDomain, testRole, "test", &flag, role)
	if err != nil {
		fmt.Println(err.Error())
		return
	}
```

error log
```
signAlgorithm: 400 Invalid Role error: ResourceException (400): {code: 400, message: "Invalid Role error: String pattern mismatch (expected "[a-zA-Z0-9_][a-zA-Z0-9_-]*")  for type SimpleName in data.signAlgorithm"}
```

**Comment by havetisyan** [comment]
Probably not using the latest go client. We changed the RDL in #2515:

https://github.com/AthenZ/athenz/releases/tag/v1.11.52

**Comment by WoWsj** [comment]
@havetisyan Thank you for quick reply. Actually, It occurs when I used `v1.11.52` client. When I changed the client version to `v1.11.9` (which is used by other code in my comapany), it works well.

**Comment by havetisyan** [comment]
so that means your server is not updated to the 1.11.52 release. before that release, it was not possible to reset the several of the role/group/domain meta attributes when using the java client so that required the relaxing of the datatype from simple name to string.

**Comment by WoWsj** [comment]
I see. When I used `GetRole`, `signAlgorithm` field returned with empty value, so I thought that it was bug or something. Anyway, I understood. Thank you very much. 😄
