### ISSUE TITLE
questions regarding ZTS's readOnlyMode

### ISSUE THREAD

**Issue by ysknkd** [AthenZ/athenz#2577]
We are in a situation where we must migrate the database used by ZTS. Additionally, due to the specifics of our database setup, we're required to switch ZTS into a read-only mode.

When I researched how ZTS operates in read-only mode, I found that it checks for this mode at the start of the postInstanceRegisterInformation() method.
https://github.com/AthenZ/athenz/blob/fce30a3d64f1808cb0156c63fac42b034db274a3/servers/zts/src/main/java/com/yahoo/athenz/zts/ZTSImpl.java#L3663-L3671

During the database migration, I want to keep its impact to a minimum, and I believe it may be beneficial to continue issuing certificates for requests that do not require certificate updates.

ZTS is designed not to write to the database when no certificate updates are needed.
https://github.com/AthenZ/athenz/blob/fce30a3d64f1808cb0156c63fac42b034db274a3/servers/zts/src/main/java/com/yahoo/athenz/zts/ZTSImpl.java#L3867-L3877

I'm wondering about the reason for checking read-only mode right at the beginning of that method. Could it be to prevent unnecessary requests to the Instance Provider?

**Comment by havetisyan** [comment]
The primary use case for the read-only mode in ZTS is actually issuing certificates. So the idea was to have the capability a way to block issuing all certificates (both identity and role) regardless of the fact what the server is configured to use for the datastore (e.g. we don't use a mysql db but rather we use DynamoDB to store the cert details).

**Comment by ysknkd** [comment]
Thank you for your response. I understand that it is used for the purpose of stopping certificate issuance. We are considering migrating ZTS without setting `readOnlyMode=true` .
