### ISSUE TITLE
Question Regarding the Specifications of Principal Group

### ISSUE THREAD

**Issue by kk0n** [AthenZ/athenz#2600]
I would like to confirm the specifications regarding the Principal Group.

https://github.com/AthenZ/athenz/blob/master/docs/principal_groups.md#group-management

> However, a role can include multiple groups as a member, and those groups could be from different domains.

Does the statement above mean that "a role can include multiple groups as members, but only one group per domain can be added to a single role"? Or is my interpretation incorrect?

**Comment by havetisyan** [comment]
The role can include any number of groups from any number of domains, for example, you might have a role:

name: readers
members:
  user.joe
  sports.api
  sports:group.dev-team
  sports:group.qa-team
  weather:group.dev-team
  weather:group.pe-team

**Comment by kk0n** [comment]
Thank you for your response. I now understand that my interpretation was incorrect.
