### ISSUE TITLE
postSubDomain supports templates without params

### ISSUE THREAD

**Issue by WoWsj** [AthenZ/athenz#2661]
## Issues

Hello, folks. 

I found out that `postSubDomain` supports templates option but there is no input scheme for params.

Without params, I don't think that `postSubDomain` is useful. Is it intentional?

**Comment by havetisyan** [comment]
It is useful for cases where you don't have variables in your templates. We have some where we just want to create predefined set of roles/services/polices that do not require any input from the user and having that capability as part of the domain creation is useful.

I think you should also be easily extend the api to accept params if that's what you're looking for.

**Comment by WoWsj** [comment]
I see. Thank you.
