### ISSUE TITLE
Athenz 1.12.x Release with upgrade to Jetty 12

### ISSUE THREAD

**Issue by havetisyan** [AthenZ/athenz#2671]
Athenz 1.12.x will include the following changes:

- Upgrade to Jetty 12.x / EE10 Release using Jakarta 6.x
- Remove all deprecated methods from server side interfaces
- Migrate all aws v1 usage from server side code to aws v2 since v1 sdk is EOL
- Migrate Apache HttpClient 4.x to 5.x
- Server builds are released w/ JDK 17 due to jetty requirement but all client libraries are continued to be built and published with JDK 11 support
- replace jjwt library with nimbus-jwt library
- CI/CD pipeline will be moved from SD to GitHub Actions
- Move AWSPrivateKeyStore implementation from server-common to auth-core where it belongs with the correct package name
- Remove single email notification support and only support consolidated email notifications (there is no point of spamming the admin with 20 separate emails where a single email can include all the roles that the admin needs to review)
- Possible package renaming [Decided NOT to make any client side changes in this release]
- * cert refresher has com.oath which doesn't match with anything else so probably a good candidate for rename
- * maybe rename server side packages to io.athenz but keep the clients using com.yahoo for another release?

**Comment by havetisyan** [comment]
The following deprecated methods have been removed from server side interfaces:

**PrivateKeyStore**

- getPrivateKey (without algorithm, returning PrivateKey)
- getApplicationSecret
- getSecret (2 args, without keygroupname)

**DynamoDBClientFetcher**

- getDynamoDBClient (without DynamoDBClientSettings argument)

**CertSigner**

- generateX509Certificate (3 versions - without key id argument)
- getCACertificate (2 versions - (without key id argument)

**SSHSigner**

- generateCertificate (without key id argument)
- getSignerCertificate (without key id argument)

**NotificationServiceFactory**

- create (without PrivateKeyStore argument)

If you're using the default implementations provided as part of the Athenz release, then no changes are necessary since those are already updated accordingly. Otherwise, for any internal implementations of these interfaces, you must make the necessary changes before deployment.

**Comment by havetisyan** [comment]
| Old Class | New Class |
| --------- | ----------- |
| com.yahoo.athenz.auth.impl.aws.AwsPrivateKeyStoreFactory | com.yahoo.athenz.auth.impl.AwsS3PrivateKeyStoreFactory |
| com.yahoo.athenz.auth.impl.aws.AwsPrivateKeyStore | com.yahoo.athenz.auth.impl.AwsS3PrivateKeyStore |

**Comment by havetisyan** [comment]
removed baseUrl argument from HttpDriver class in the athenz_server_common library since it was not used.

**Comment by gyakami** [comment]
@havetisyan 
The docker build also fails in our environment for the same reasons as the actions below. 
https://github.com/AthenZ/athenz/actions/runs/11227301734/job/31209305932
Has any action been considered for this?

**Comment by havetisyan** [comment]
That's already fixed in the following PR: https://github.com/AthenZ/athenz/pull/2763 We just haven't merged it yet since the action only runs when there is an official release.

**Comment by ysknkd** [comment]
@havetisyan 
I was wondering if these might also need to be addressed. Could you please take a look?
https://github.com/AthenZ/athenz/blob/a3583ee7131fb20ae6b19901b5a243e2ef32225d/docker/util/athenz-mvn-base/Dockerfile#L11
https://github.com/AthenZ/athenz/blob/a3583ee7131fb20ae6b19901b5a243e2ef32225d/docker/util/athenz-builder/Dockerfile#L1

**Comment by havetisyan** [comment]
https://github.com/AthenZ/athenz/blob/master/docs/migration-1.11-to-1.12.md
