### ISSUE TITLE
ZTS Docker Image does not bundle the athenz-instance-provider library

### ISSUE THREAD

**Issue by ysknkd** [AthenZ/athenz#2818]
The docker image does not bundle the instance-provider library `athenz-instance-provider` , which causes the instanceZTSProvider to not function.

As far as I have confirmed, it seems that the instance-provider is no longer bundled from version 1.12.x. Instead of the instance-provider, the athenz-zts-java-client is now bundled.

```bash
$ docker run --rm --entrypoint="" athenz/athenz-zts-server:1.11.66 ls -la /opt/athenz/zts/lib/jars | grep athenz
-rw-r--r-- 1 root root   151173 Sep 28 22:05 athenz-auth-core-1.11.66.jar
-rw-r--r-- 1 root root    21232 Sep 28 22:07 athenz-cert-refresher-1.11.66.jar
-rw-r--r-- 1 root root    26681 Sep 28 22:06 athenz-client-common-1.11.66.jar
-rw-r--r-- 1 root root   103002 Sep 28 22:12 athenz-instance-provider-1.11.66.jar
-rw-r--r-- 1 root root    27800 Sep 28 22:20 athenz-jetty-container-1.11.66.jar
-rw-r--r-- 1 root root    74662 Sep 28 22:04 athenz-msd-core-1.11.66.jar
-rw-r--r-- 1 root root   259566 Sep 28 22:10 athenz-server-common-1.11.66.jar
-rw-r--r-- 1 root root   169566 Sep 28 22:02 athenz-zms-core-1.11.66.jar
-rw-r--r-- 1 root root    63772 Sep 28 22:08 athenz-zms-java-client-1.11.66.jar
-rw-r--r-- 1 root root    85595 Sep 28 22:03 athenz-zts-core-1.11.66.jar

$  docker run --rm --entrypoint="" athenz/athenz-zts-server:1.12.2 ls -la /opt/athenz/zts/lib/jars | grep athenz
-rw-r--r-- 1 root root   153565 Oct 18 02:27 athenz-auth-core-1.12.2.jar
-rw-r--r-- 1 root root    21486 Oct 18 02:28 athenz-cert-refresher-1.12.2.jar
-rw-r--r-- 1 root root    27031 Oct 18 02:28 athenz-client-common-1.12.2.jar
-rw-r--r-- 1 root root    27399 Oct 18 02:42 athenz-jetty-container-1.12.2.jar
-rw-r--r-- 1 root root    75473 Oct 18 02:25 athenz-msd-core-1.12.2.jar
-rw-r--r-- 1 root root   375813 Oct 18 02:32 athenz-server-common-1.12.2.jar
-rw-r--r-- 1 root root   171287 Oct 18 02:23 athenz-zms-core-1.12.2.jar
-rw-r--r-- 1 root root    66644 Oct 18 02:29 athenz-zms-java-client-1.12.2.jar
-rw-r--r-- 1 root root    86354 Oct 18 02:24 athenz-zts-core-1.12.2.jar
-rw-r--r-- 1 root root    89955 Oct 18 02:30 athenz-zts-java-client-1.12.2.jar
```

**Comment by havetisyan** [comment]
This is most likely due to clean up in the jetty container module where it no longer depends on modules that it doesn't need. I'll take a look.

**Comment by havetisyan** [comment]
$ docker run --rm --entrypoint="" athenz/athenz-zts-server:1.12.6 ls -la /opt/athenz/zts/lib/jars | grep athenz
-rw-r--r-- 1 root root  154767 Dec  7 01:18 athenz-auth-core-1.12.6.jar
-rw-r--r-- 1 root root   21486 Dec  7 01:20 athenz-cert-refresher-1.12.6.jar
-rw-r--r-- 1 root root   27031 Dec  7 01:19 athenz-client-common-1.12.6.jar
-rw-r--r-- 1 root root  110347 Dec  7 01:28 athenz-instance-provider-1.12.6.jar
-rw-r--r-- 1 root root   27909 Dec  7 01:32 athenz-jetty-container-1.12.6.jar
-rw-r--r-- 1 root root   75473 Dec  7 01:17 athenz-msd-core-1.12.6.jar
-rw-r--r-- 1 root root  366360 Dec  7 01:23 athenz-server-common-1.12.6.jar
-rw-r--r-- 1 root root  172712 Dec  7 01:15 athenz-zms-core-1.12.6.jar
-rw-r--r-- 1 root root   66965 Dec  7 01:21 athenz-zms-java-client-1.12.6.jar
-rw-r--r-- 1 root root   86355 Dec  7 01:16 athenz-zts-core-1.12.6.jar
-rw-r--r-- 1 root root   89939 Dec  7 01:22 athenz-zts-java-client-1.12.6.jar
