### ISSUE TITLE
Move to aws-sdk-java-v2

### ISSUE THREAD

**Issue by anilkumarmyla** [AthenZ/athenz#939]
It's been a while since aws sdk v2 came out https://github.com/aws/aws-sdk-java-v2 and boasts better features including non-blocking IO. Not that it is a needed feature, but would be good to move to v2 sdk

**Comment by havetisyan** [comment]
I'm assuming this is in reference to ZTS client and it supports credentials providers for both v1 and v2 of AWS SDK for Java.
